language: php

php:
  - 5.2
  - 5.3
  - 5.4

env:
  - DB=mysql

before_script:
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS woola;" -uroot; fi

script: phpunit --coverage-text

notifications:
  email:
    - travis-ci@liip.ch